### PR TITLE
Compatibility with phpspec 4.3.0, symfony >4.0.0, JoliNotif >2.0.0

### PR DESCRIPTION
**Pull request by mmswiderski**

### CODE REVIEW

**Comment by fetzi** [comment]
fixes #3

**Comment by fetzi** [comment]
Thanks for the PR. We should use the same versions as phpspec uses. Therefor please change the 3 symfony dependencies to "^3.2 || ^4.0". Otherwise we would only be compatible with the 4.x versions. Thanks in advance.

**Comment by mmswiderski** [comment]
Done. 
You are right I did not think about backward compatibility. Fixed.

**Comment by fetzi** [comment]
Perfect, thanks a lot!

**Pull request merged**
